version: "2.4"

services:

  api:
    image: scaleshift/api:local
    build:
      context: ../../
      dockerfile: tools/prod/api.Dockerfile
      args:
        BASE_IMAGE: scaleshift/api:cache
      target: builder
    entrypoint: tini -- sleep 31536000
    ports:
      - 9000:80
    environment:
      - SS_RESCALE_ENDPOINT=https://platform.rescale.jp
      - SS_RESCALE_API_TOKEN
      - SS_LOG_LEVEL=debug
      - SS_LOG_FORMAT=json
      - SS_MAX_WORKERS=4
      - SS_MUST_SIGN_IN=false
      - SS_IMAGES_TOBE_IGNORED=scaleshift/,ss-jupyter/,supinf/,<none>
      - SS_WORKSPACE_HOST_DIR=${PWD}/tools/dev/tmp/work
      - SS_SINGULARITY_HOST_DIR=${PWD}/tools/dev/tmp/simg
      - SS_DATABASE_ENDPOINT=user:pass@tcp(scaleshift_db:3306)/scaleshift?charset=utf8mb4&collation=utf8_unicode_ci&parseTime=true
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - ../../api/certs:/certs
      - ./tmp/db:/tmp/badger
      - ./tmp/simg:/tmp/simg
      - ./tmp/work:/tmp/work
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /go/src/github.com/scaleshift/scaleshift/api/src
    networks:
      - services
    restart: always
    container_name: scaleshift_api

  web:
    image: supinf/hugo:0.x
    command: server --bind=0.0.0.0 -p=80 -b=http://localhost:8080/ --appendPort=false --disableLiveReload
    volumes:
      - ../../web/src:/app
    logging:
      driver: none
    networks:
      - services
    restart: always
    container_name: scaleshift_web

  proxy:
    image: scaleshift/proxy:1.10
    ports:
      - 8080:80
    logging:
      driver: none
    networks:
      - services
    restart: always
    container_name: scaleshift_proxy

  gulp:
    image: scaleshift/gulp:local-20191003
    build: docker/gulp
    volumes:
      - ../../web:/monitor/web
      - /var/run/docker.sock:/var/run/docker.sock
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"
    ulimits:
      cpu:
        soft: 20
        hard: 40
    networks:
      - services
    restart: always
    container_name: scaleshift_gulp

networks:
  services:
    external:
      name: dev_scaleshift_network
